### ISSUE TITLE
Mobile view is not showing result properly 

### ISSUE THREAD

**Issue by HemangVora** [adithyapaib/downloadTimeCalculator#139]
![image](https://user-images.githubusercontent.com/38496991/136252418-2731de74-0d18-4329-ba6b-4ea6704f766c.png)
Hi @adithyapaib  there is issue when result displays on mobile view green background is not in full result also calculate new button is merging with footer. I can fix this issue please assign it to me.

**Comment by Rashmisingh-18** [comment]
Hey @adithyapaib , could you please assign this to me, I think I can change mobile view of that repo.

**Comment by AnshuPathak-88825** [comment]
@adithyapaib please assign me this issues I can fix it

**Comment by hemang98** [comment]
> hey @adithyapaib , #146 I have resolved this issue and did some changes in it. Please check it and accept my pull requests.

> Hi Rashmi I have already resolved this issue and raised PR also I was going through your changes it was too many for this small issue.
