### ISSUE TITLE
There is two download time Predictor form in one page 

### ISSUE THREAD

**Issue by md-jishan-ansari** [adithyapaib/downloadTimeCalculator#148]
Both bigger and smaller screen have two Download time Predictor form this is bad user experience
![WhatsApp Image 2021-10-07 at 9 38 23 PM (1)](https://user-images.githubusercontent.com/86798430/136423951-de03c5d5-27e3-4296-a8c4-6e8a4e73e150.jpeg)

**Comment by rishabhj0110** [comment]
Can you assign me this issue?
