### ISSUE TITLE
social media icons in about page

### ISSUE THREAD

**Issue by rishika789** [adithyapaib/downloadTimeCalculator#154]
The icons are not identical in shape and size I would like to change it.

![image](https://user-images.githubusercontent.com/78673968/136642447-5f53bd62-c4d4-4bd2-a638-612921c97bca.png)

**Comment by Shobhit61730** [comment]
Hello, I would like to work on this issue.

**Comment by Ritika1800** [comment]
hey, Please assign this issue to me.
