### ISSUE TITLE
Change UI of output BOX

### ISSUE THREAD

**Issue by Bhawna147** [adithyapaib/downloadTimeCalculator#180]
Slight changes in the output box can make it look better like the button Calculate new  is not properly visible
![image](https://user-images.githubusercontent.com/79100530/136914551-9dffbff6-9941-4b7f-834c-f3618dfb26df.png)

I'll make it look somewhat like this 
![image](https://user-images.githubusercontent.com/79100530/136916333-55b6a6da-bcbd-469e-b374-808feee263c6.png)
I'll also add a box to the mid text so that the Result will be highlighted. @adithyapaib  Please assign this issue to me to make the following changes.

**Comment by imps1001** [comment]
Hey @adithyapaib, Kindly assign it to me. As a front-end developer, I can transform its UI into a better one. Kindly assign it to me.
