### ISSUE TITLE
Navbar of Web Page

### ISSUE THREAD

**Issue by shrishti-c** [adithyapaib/downloadTimeCalculator#184]
![Screenshot (60)](https://user-images.githubusercontent.com/73748606/137089104-f1633c13-a199-4066-805e-012be5a2faab.png)
![Screenshot (61)](https://user-images.githubusercontent.com/73748606/137089115-b11497db-f817-40b4-8a40-5cd5197f70ad.png)
![Screenshot (62)](https://user-images.githubusercontent.com/73748606/137089119-d33384b5-8410-43a8-be4a-1e21f7cc408e.png)

NavBar keeps changing on different page. I'll make it same and About Us section doesn't work in File Transfer section. I'll fix that too.

Please assign me this under HacktoberFest Tag.

**Comment by yas-sisodia** [comment]
@adithyapaib can you this task to me
