### ISSUE TITLE
Issues with about page

### ISSUE THREAD

**Issue by sarthakahuja07** [adithyapaib/downloadTimeCalculator#200]
![image](https://user-images.githubusercontent.com/82509612/137547022-26498976-9272-4fdf-a8ea-338f646be3f7.png)

**Comment by sarthakahuja07** [comment]
@adithyapaib Hi, I can work on this issue, can u assign it to me

**Comment by Shobhit61730** [comment]
Please assign this issue to me .I will definitely fix it.

**Comment by Shobhit61730** [comment]
Recently I fixed this issue please assign this to me. So that I will send you pull request .
Please assign me......

**Comment by sarthakahuja07** [comment]
@Shobhit61730 I am almost done
