### ISSUE TITLE
Add Some CSS on  Submit button like change color , little bit zoom and add some shadow on hovering  .

### ISSUE THREAD

**Issue by AnuragRoshan** [adithyapaib/downloadTimeCalculator#26]
it will improve its UI

**Comment by aman-netizen** [comment]
Can you please assign me this issue I can do it.

**Comment by adithyapaib** [comment]
Assigned

**Comment by swaraj-ssk** [comment]
Can add all these. Interested to contribute.

**Comment by coder483** [comment]
can i work on this

**Comment by adithyapaib** [comment]
Assigined everyone share the task and contribute

**Comment by ayushjain27** [comment]
Please assign me

**Comment by adithyapaib** [comment]
> Please assign me

Done

**Comment by roc-cyber** [comment]
Can you please assign me to work on this?

**Comment by adithyapaib** [comment]
> Can you please assign me to work on this?

Done

**Comment by Dcode-k** [comment]
@adithyapaib can you please assign it to me?

**Comment by Radhey100** [comment]
Assign me

**Comment by mansi-singla-31215** [comment]
@adithyapaib can you please assign this task to me?

**Comment by RishiRajKhanna2511** [comment]
Please assign it to me.

**Comment by devangpawar17** [comment]
assign this task to me

**Comment by Priyanshi-Raj** [comment]
Can you please assign me this .

**Comment by Ritika457** [comment]
Can you please assign this issue to me. I can fix this

**Comment by adithyapaib** [comment]
Assigined all pls share the work and pr accordingly

**Comment by mansi-singla-31215** [comment]
@adithyapaib I have made the pr, please check it.

**Comment by biohazard2117** [comment]
Assign this task to me please @adithyapaib .

**Comment by biohazard2117** [comment]
@adithyapaib There are 2 index.html files. So in which one do you want us to make changes?
