### ISSUE TITLE
Reducing the User Inputs.

### ISSUE THREAD

**Issue by mahesh-biswas** [adithyapaib/downloadTimeCalculator#38]
Hey @adithyapaib, I have made some changes where in I have removed the Submit button and the calculations are performed automatically on change of input. This will remove the User input.

Also, I have created a new page for the same and linked that via the navigation link (from main page to the new page and vice-versa)
![image](https://user-images.githubusercontent.com/25072269/135745693-b2353cb2-db95-4ff1-9305-97e03ff7260b.png)

**Comment by mahesh-biswas** [comment]
raised a PR for the same.

**Comment by Pratim14** [comment]
Assign me this
