### ISSUE TITLE
Changing the color code

### ISSUE THREAD

**Issue by Khushi-Shukla** [adithyapaib/downloadTimeCalculator#52]
The colors red and green along with the black text does not look properly color coded. I wanted to change the font and color of the div having green color . Please assign me this issue.

**Comment by adithyapaib** [comment]
Sure go ahead

**Comment by Paawan9700** [comment]
actually the UI can be improved further so can i take this issue?

**Comment by Khushi-Shukla** [comment]
Please review and merge PR #64

**Comment by Priyanshi-Raj** [comment]
@adithyapaib Please can I work on this issue?
