### ISSUE TITLE
REMOVE unused nav elements 

### ISSUE THREAD

**Issue by adithyapaib** [adithyapaib/downloadTimeCalculator#58]

**Comment by alberturria** [comment]
Hey @adithyapaib can I take a look at it?

**Comment by biohazard2117** [comment]
Hello @adithyapaib may be I can do it...Assign it to me please.

**Comment by Paawan9700** [comment]
can i take this issue?

**Comment by Dcode-k** [comment]
@adithyapaib Please can I work on this issue?

**Comment by ritwik3856** [comment]
can you assign me this

**Comment by Priyanshi-Raj** [comment]
@adithyapaib Please can I work on this issue?

**Comment by ritwik3856** [comment]
Can explain more about the issue

**Comment by Pratim14** [comment]
Kindly assign this issue

**Comment by adithyapaib** [comment]
> Can explain more about the issue

Remove all extra things  from nav bar
