### ISSUE TITLE
Issue with the color of the submit button

### ISSUE THREAD

**Issue by Krrishnaa25** [adithyapaib/downloadTimeCalculator#72]
The submit button is initially black, on entering dark mode it becomes green but on reverting back to light mode, the color still stays green. Assign me this issue.

**Comment by adithyapaib** [comment]
Done

**Comment by ShubhashishMaiti** [comment]
@adithyapaib I would love to work on this issue. Would you please assign this issue to me?

**Comment by yas-sisodia** [comment]
@adithyapaib Can you assign this task me I can do this
