### ISSUE TITLE
After clicking submit button heading download time predictor go inside navbar

### ISSUE THREAD

**Issue by aman-netizen** [adithyapaib/downloadTimeCalculator#79]
When anybody click on submit heading goes in navbar and also that box open after click touches footer I want to resolve this issue please assign me this.

**Comment by rounit08** [comment]
@adithyapaib Can I take This?

**Comment by aman-netizen** [comment]
Hi @adithyapaib I resolve this issue and some more changes in pull request #99 please review it.
